.TH "ao_driver_t" 3 "17 Sep 2001" "XINE, A Free Video Player Project - API reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ao_driver_t \- 
.SH SYNOPSIS
.br
.PP
\fC#include <xine.h>\fP
.PP
.SH "DETAILED DESCRIPTION"
.PP 
Opaque data type. 
.PP


.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for XINE, A Free Video Player Project - API reference from the source code.