.TH "Autoplay support" 3 "15 Oct 2001" "XINE, A Free Video Player Project - API reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Autoplay support \- 
.SS "Functions"

.in +1c
.ti -1c
.RI "char** \fBxine_get_autoplay_input_plugin_ids\fP (\fBxine_t\fP *self)"
.br
.RI "\fIRequest playlist from plugin.\fP"
.ti -1c
.RI "char** \fBxine_get_autoplay_mrls\fP (\fBxine_t\fP *self, char *plugin_id, int *num_mrls)"
.br
.RI "\fIRequest MRL list from plugin.\fP"
.in -1c
.SH "FUNCTION DOCUMENTATION"
.PP 
.SS "char ** xine_get_autoplay_input_plugin_ids (\fBxine_t\fP * self)"
.PP
Request playlist from plugin.
.PP
\fBParameters: \fP
.in +1c
.TP
\fB\fIself\fP\fP
Current xine engine configuration ( see \fBxine_init\fP() ) 
.PP
\fBReturns: \fP
.in +1c
Playlist.
.PP
Some input plugins can generate autoplay lists returns a list of ids of these plugins. 
.PP
\fBParameters: \fP
.in +1c
.TP
\fB\fIself\fP\fP
 
.SS "char ** xine_get_autoplay_mrls (\fBxine_t\fP * self, char * plugin_id, int * num_mrls)"
.PP
Request MRL list from plugin.
.PP
\fBParameters: \fP
.in +1c
.TP
\fB\fIself\fP\fP
Current xine engine configuration ( see \fBxine_init\fP() ) 
.TP
\fB\fIplugin_id\fP\fP
Plugin name ( see \fBxine_get_autoplay_input_plugin_ids\fP() ) 
.TP
\fB\fInum_mrls\fP\fP
Entries in return array. 
.PP
\fBReturns: \fP
.in +1c
MRL list.
.PP
Get autoplay MRL list for input plugin named <plugin_id>. 
.PP
\fBParameters: \fP
.in +1c
.TP
\fB\fIself\fP\fP
 
.TP
\fB\fIplugin_id\fP\fP
 
.TP
\fB\fInum_mrls\fP\fP
 