.TH "Build informations" 3 "26 Jul 2001" "XINE, A Free Video Player Project - API reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Build informations \- 
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBXINE_BUILD_CC\fP   'gcc version 2.95.3 20010315 (release)'"
.br
.ti -1c
.RI "#define \fBXINE_BUILD_OS\fP   'Linux 2.4.5 i686'"
.br
.ti -1c
.RI "#define \fBXINE_BUILD_DATE\fP   'Thu 26 Jul 2001 09:17:10'"
.br
.in -1c
.SH "DEFINE DOCUMENTATION"
.PP 
.SS "#define XINE_BUILD_CC   'gcc version 2.95.3 20010315 (release)'"
.PP
Compiler used to build xine-lib 
.SS "#define XINE_BUILD_DATE   'Thu 26 Jul 2001 09:17:10'"
.PP
Build time 
.SS "#define XINE_BUILD_OS   'Linux 2.4.5 i686'"
.PP
OS used to build xine-lib 