.TH "Configuration structure type." 3 "26 Jul 2001" "XINE, A Free Video Player Project - API reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Configuration structure type. \- 
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBao_functions_t\fP"
.br
.ti -1c
.RI "struct \fBcfg_data_t\fP"
.br
.ti -1c
.RI "struct \fBconfig_values_s\fP"
.br
.ti -1c
.RI "struct \fBconfig_values_s\fP"
.br
.ti -1c
.RI "struct \fBconfig_values_t\fP"
.br
.RI "\fIData type of structure \fBconfig_values_s\fP.\fP"
.ti -1c
.RI "struct \fBxine_t\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void \fBxine_t\fP"
.br
.ti -1c
.RI "typedef void \fBao_functions_t\fP"
.br
.ti -1c
.RI "typedef void \fBcfg_data_t\fP"
.br
.ti -1c
.RI "typedef struct \fBconfig_values_s\fP \fBconfig_values_t\fP"
.br
.in -1c