.TH "config_values_t" 3 "17 Sep 2001" "XINE, A Free Video Player Project - API reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
config_values_t \- Data type of structure \fBconfig_values_s\fP. 
.SH SYNOPSIS
.br
.PP
\fC#include <xine.h>\fP
.PP
.SH "DETAILED DESCRIPTION"
.PP 
Data type of structure \fBconfig_values_s\fP.
.PP
\fBSee also: \fP
.in +1c
\fBconfig_values_s\fP. 
.PP


.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for XINE, A Free Video Player Project - API reference from the source code.