.TH "mrl_t" 3 "17 Sep 2001" "XINE, A Free Video Player Project - API reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mrl_t \- 
.SH SYNOPSIS
.br
.PP
\fC#include <xine.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char* \fBorigin\fP"
.br
.ti -1c
.RI "char* \fBmrl\fP"
.br
.ti -1c
.RI "char* \fBlink\fP"
.br
.ti -1c
.RI "uint32_t \fBtype\fP"
.br
.ti -1c
.RI "off_t \fBsize\fP"
.br
.in -1c
.SH "DETAILED DESCRIPTION"
.PP 
mrl type. 
.PP
\fBSee also: \fP
.in +1c
\fBxine_get_browse_mrls\fP(), \fBMRL_ZERO\fP, \fBMRL_DUPLICATE\fP, \fBMRLS_DUPLICATE\fP, Types of available mrls 
.PP
.SH "FIELD DOCUMENTATION"
.PP 
.SS "char * mrl_t::link"
.PP
name of link, if exist, otherwise NULL 
.SS "char * mrl_t::mrl"
.PP
<type>://<location> 
.SS "char * mrl_t::origin"
.PP
Origin of grabbed mrls (eg: path for file plugin 
.SS "off_t mrl_t::size"
.PP
size of this source, may be 0 
.SS "uint32_t mrl_t::type"
.PP
match to mrl_type enum 

.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for XINE, A Free Video Player Project - API reference from the source code.