.TH "Player status constants" 3 "26 Jul 2001" "XINE, A Free Video Player Project - API reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Player status constants \- 
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBXINE_STOP\fP   0"
.br
.ti -1c
.RI "#define \fBXINE_PLAY\fP   1"
.br
.ti -1c
.RI "#define \fBXINE_PAUSE\fP   2"
.br
.ti -1c
.RI "#define \fBXINE_QUIT\fP   3"
.br
.in -1c
.SH "DEFINE DOCUMENTATION"
.PP 
.SS "#define XINE_PAUSE   2"
.PP
Pause status. 
.PP
\fBSee also: \fP
.in +1c
\fBxine_get_status\fP() 
.SS "#define XINE_PLAY   1"
.PP
Play status. 
.PP
\fBSee also: \fP
.in +1c
\fBxine_get_status\fP() 
.SS "#define XINE_QUIT   3"
.PP
Quit status. 
.PP
\fBSee also: \fP
.in +1c
\fBxine_get_status\fP() 
.SS "#define XINE_STOP   0"
.PP
Stop status. 
.PP
\fBSee also: \fP
.in +1c
\fBxine_get_status\fP() 