.TH "Version constants" 3 "15 Oct 2001" "XINE, A Free Video Player Project - API reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Version constants \- 
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBXINE_MAJOR_VERSION\fP   0"
.br
.ti -1c
.RI "#define \fBXINE_MINOR_VERSION\fP   9"
.br
.ti -1c
.RI "#define \fBXINE_SUB_VERSION\fP   2"
.br
.in -1c
.SH "DEFINE DOCUMENTATION"
.PP 
.SS "#define XINE_MAJOR_VERSION   0"
.PP
Major version constant. 
.SS "#define XINE_MINOR_VERSION   9"
.PP
Minor version constant. 
.SS "#define XINE_SUB_VERSION   2"
.PP
Sub version constant. 