.TH "Video." 3 "26 Jul 2001" "XINE, A Free Video Player Project - API reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Video. \- 
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBPossible ratios for the VO_PROP_ASPECT_RATIO call\fP"
.br
.ti -1c
.RI "\fBConstants for the get/set properties functions.\fP"
.br
.ti -1c
.RI "\fBvideo driver capabilities\fP"
.br
.in -1c
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBvo_driver_s\fP"
.br
.ti -1c
.RI "struct \fBvo_driver_s\fP"
.br
.ti -1c
.RI "struct \fBvo_driver_t\fP"
.br
.RI "\fIData type of structure \fBvo_driver_s\fP.\fP"
.ti -1c
.RI "struct \fBvo_frame_t\fP"
.br
.ti -1c
.RI "struct \fBvo_overlay_t\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void \fBvo_frame_t\fP"
.br
.ti -1c
.RI "typedef void \fBvo_overlay_t\fP"
.br
.ti -1c
.RI "typedef struct \fBvo_driver_s\fP \fBvo_driver_t\fP"
.br
.in -1c