.TH "video driver capabilities" 3 "17 Sep 2001" "XINE, A Free Video Player Project - API reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
video driver capabilities \- 
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBVO_CAP_HUE\fP   0x00000010"
.br
.ti -1c
.RI "#define \fBVO_CAP_SATURATION\fP   0x00000020"
.br
.ti -1c
.RI "#define \fBVO_CAP_BRIGHTNESS\fP   0x00000040"
.br
.ti -1c
.RI "#define \fBVO_CAP_CONTRAST\fP   0x00000080"
.br
.ti -1c
.RI "#define \fBVO_CAP_COLORKEY\fP   0x00000100"
.br
.in -1c
.SH "DEFINE DOCUMENTATION"
.PP 
.SS "#define VO_CAP_BRIGHTNESS   0x00000040"
.PP
Driver can set BRIGHTNESS value. 
.SS "#define VO_CAP_COLORKEY   0x00000100"
.PP
Driver can set COLORKEY value. 
.SS "#define VO_CAP_CONTRAST   0x00000080"
.PP
Driver can set CONTRAST value. 
.SS "#define VO_CAP_HUE   0x00000010"
.PP
Driver can set HUE value. 
.SS "#define VO_CAP_SATURATION   0x00000020"
.PP
Driver can set SATURATION value. 