.TH "Possible ratios for the VO_PROP_ASPECT_RATIO call" 3 "26 Jul 2001" "XINE, A Free Video Player Project - API reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Possible ratios for the VO_PROP_ASPECT_RATIO call \- 
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBASPECT_AUTO\fP   0"
.br
.ti -1c
.RI "#define \fBASPECT_ANAMORPHIC\fP   1"
.br
.ti -1c
.RI "#define \fBASPECT_FULL\fP   2"
.br
.ti -1c
.RI "#define \fBASPECT_DVB\fP   3"
.br
.in -1c
.SH "DETAILED DESCRIPTION"
.PP 
\fBSee also: \fP
.in +1c
\fBVO_PROP_ASPECT_RATIO\fP, \fBvo_driver_t\fP 
.SH "DEFINE DOCUMENTATION"
.PP 
.SS "#define ASPECT_ANAMORPHIC   1"
.PP
Set aspect ration to 16:9. 
.PP
\fBSee also: \fP
.in +1c
\fBVO_PROP_ASPECT_RATIO\fP 
.SS "#define ASPECT_AUTO   0"
.PP
Let video driver guessing aspect ratio. 
.PP
\fBSee also: \fP
.in +1c
\fBVO_PROP_ASPECT_RATIO\fP 
.SS "#define ASPECT_DVB   3"
.PP
Set aspect ration to 1:2. 
.PP
\fBSee also: \fP
.in +1c
\fBVO_PROP_ASPECT_RATIO\fP 
.SS "#define ASPECT_FULL   2"
.PP
Set aspect ration to 4:3. 
.PP
\fBSee also: \fP
.in +1c
\fBVO_PROP_ASPECT_RATIO\fP 