.TH "Valid visual types" 3 "26 Jul 2001" "XINE, A Free Video Player Project - API reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Valid visual types \- 
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBVISUAL_TYPE_X11\fP   1"
.br
.ti -1c
.RI "#define \fBVISUAL_TYPE_AA\fP   2"
.br
.ti -1c
.RI "#define \fBVISUAL_TYPE_FB\fP   3"
.br
.ti -1c
.RI "#define \fBVISUAL_TYPE_GTK\fP   4"
.br
.in -1c
.SH "DEFINE DOCUMENTATION"
.PP 
.SS "#define VISUAL_TYPE_AA   2"
.PP
Asci Art visual type. 
.PP
\fBSee also: \fP
.in +1c
\fBxine_list_video_output_plugins\fP, \fBxine_load_video_output_plugin\fP 
.SS "#define VISUAL_TYPE_FB   3"
.PP
Framebuffer visual type 
.PP
\fBSee also: \fP
.in +1c
\fBxine_list_video_output_plugins\fP, \fBxine_load_video_output_plugin\fP 
.SS "#define VISUAL_TYPE_GTK   4"
.PP
GTK visual type 
.PP
\fBSee also: \fP
.in +1c
\fBxine_list_video_output_plugins\fP, \fBxine_load_video_output_plugin\fP 
.SS "#define VISUAL_TYPE_X11   1"
.PP
X11 visual type. 
.PP
\fBSee also: \fP
.in +1c
\fBxine_list_video_output_plugins\fP, \fBxine_load_video_output_plugin\fP 