.TH "vo_driver_t" 3 "15 Oct 2001" "XINE, A Free Video Player Project - API reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vo_driver_t \- Data type of structure \fBvo_driver_s\fP. 
.SH SYNOPSIS
.br
.PP
\fC#include <xine.h>\fP
.PP
.SH "DETAILED DESCRIPTION"
.PP 
Data type of structure \fBvo_driver_s\fP.
.PP
\fBSee also: \fP
.in +1c
structure \fBvo_driver_s\fP. 
.PP


.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for XINE, A Free Video Player Project - API reference from the source code.