.TH "vo_frame_t" 3 "26 Jul 2001" "XINE, A Free Video Player Project - API reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vo_frame_t \- 
.SH SYNOPSIS
.br
.PP
\fC#include <xine.h>\fP
.PP
.SH "DETAILED DESCRIPTION"
.PP 
Opaque data type. 
.PP
\fBSee also: \fP
.in +1c
\fBvo_driver_t\fP 
.PP


.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for XINE, A Free Video Player Project - API reference from the source code.