.TH "Version functions" 3 "26 Jul 2001" "XINE, A Free Video Player Project - API reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Version functions \- 
.SS "Functions"

.in +1c
.ti -1c
.RI "char* \fBxine_get_str_version\fP (void)"
.br
.RI "\fIreturn string version, like '0.5.0'.\fP"
.ti -1c
.RI "int \fBxine_get_major_version\fP (void)"
.br
.RI "\fIreturn version information.\fP"
.ti -1c
.RI "int \fBxine_get_minor_version\fP (void)"
.br
.RI "\fIreturn version information.\fP"
.ti -1c
.RI "int \fBxine_get_sub_version\fP (void)"
.br
.RI "\fIreturn version information.\fP"
.ti -1c
.RI "int \fBxine_check_version\fP (int major, int minor, int sub)"
.br
.RI "\fIcheck minimal version.\fP"
.in -1c
.SH "FUNCTION DOCUMENTATION"
.PP 
.SS "int xine_check_version (int major, int minor, int sub)"
.PP
check minimal version.
.PP
\fBParameters: \fP
.in +1c
.TP
\fB\fImajor\fP\fP
major version wanted. 
.TP
\fB\fIminorr\fP\fP
minor version wanted. 
.TP
\fB\fIsub\fP\fP
sub version wanted. 
.PP
\fBReturns: \fP
.in +1c
1 if installed version is >= to desired, otherwise 0
.PP
Compare version numbers with xine installed version. 
.PP
\fBParameters: \fP
.in +1c
.TP
\fB\fImajor\fP\fP
 
.TP
\fB\fIminor\fP\fP
 
.TP
\fB\fIsub\fP\fP
 
.SS "int xine_get_major_version (void)"
.PP
return version information.
.PP
\fBParameters: \fP
.in +1c
.TP
\fB\fINone.\fP\fP
\fBReturns: \fP
.in +1c
major version. 
.SS "int xine_get_minor_version (void)"
.PP
return version information.
.PP
\fBParameters: \fP
.in +1c
.TP
\fB\fINone.\fP\fP
\fBReturns: \fP
.in +1c
minor version. 
.SS "char * xine_get_str_version (void)"
.PP
return string version, like '0.5.0'.
.PP
\fBParameters: \fP
.in +1c
.TP
\fB\fINone.\fP\fP
\fBReturns: \fP
.in +1c
string version 
.SS "int xine_get_sub_version (void)"
.PP
return version information.
.PP
\fBParameters: \fP
.in +1c
.TP
\fB\fINone.\fP\fP
\fBReturns: \fP
.in +1c
sub version. 