.TH "API functions" 3 "17 Sep 2001" "XINE, A Free Video Player Project - API reference" \" -*- nroff -*-
.ad l
.nh
.SH NAME
API functions \- 
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBSending events\fP"
.br
.ti -1c
.RI "\fBLoading plugins\fP"
.br
.ti -1c
.RI "\fBAutoplay support\fP"
.br
.ti -1c
.RI "\fBBrowsing support\fP"
.br
.ti -1c
.RI "\fBEngine management\fP"
.br
.ti -1c
.RI "\fBInit functions\fP"
.br
.ti -1c
.RI "\fBVideo.\fP"
.br
.ti -1c
.RI "\fBVersion functions\fP"
.br
.ti -1c
.RI "\fBVersion constants\fP"
.br
.ti -1c
.RI "\fBPlayer status constants\fP"
.br
.in -1c