#! /usr/bin/perl -w

=head1 NAME

dh_xine - calculates xine-lib dependencies

=cut

use strict;
use Debian::Debhelper::Dh_Lib;

=head1 SYNOPSIS

B<dh_xine> [S<I<debhelper options>>]

=head1 DESCRIPTION

dh_xine is a debhelper program that is responsible for generating the
${xine-x:Depends} and ${xine-console:Depends} substitutions and adding them
to substvars files.

Each xine-lib front end is required to have one of these two substvars
listed in its Depends line in debian/control. Using package names directly
will, sooner or later, break.

=head1 CONFORMS TO

Debian policy, version 3.8.1

=cut

init ();

my $version;

foreach my $package (@{$dh{DOPACKAGES}}) {
  my $tmp = tmpdir ($package);

  delsubstvar($package, 'xine-x:Depends');
  addsubstvar ($package, 'xine-x:Depends', 'libxine2-x');

  delsubstvar($package, 'xine-console:Depends');
  addsubstvar ($package, 'xine-console:Depends', 'libxine2-console');
}

=head1 SEE ALSO

L<debhelper(7)>

This program is not a part of debhelper.

=head1 AUTHOR

Darren Salt <linux@youmustbejoking.demon.co.uk>

=cut
