.\" -*-Nroff-*-
.\""
.TH XINE 3x 2000-11-19 "The xine project"
.SH NAME
xine-lib \- xine API.
.SH AVAILABLE MAN PAGES
.B ao_functions_t

.B autoplay_group

.B browse_group

.B build_info

.B cfg_data_t

.B config_group

.B config_values_s

.B config_values_t

.B demux_strategy

.B event_group

.B loadplugins_group

.B mrl_t

.B mrl_types

.B status_group

.B ui_callbacks

.B version_group

.B video_cap

.B video_group

.B video_prop

.B video_ratio

.B visual_types

.B vo_driver_s

.B vo_driver_t

.B vo_frame_t

.B vo_overlay_t

.B xine.h

.B xine_api

.B xine_init

.B xine_management

.B xine_t

.B xine_version

